First draft of 4.2 update
QubesOS/qubes-dist-upgrade pull request #11
Opened 2023-07-19 12:03 UTC by marmarta

First draft of update script from 4.1 to 4.2

2023-07-25 00:51 UTC, marmarek requested changes

2023-07-25 00:51 UTC, marmarek commented on qubes-dist-upgrade.sh
> +if ! OPTS=$(getopt -o htrlsgydu:n:f:jkp --long help,all,update,template-standalone-upgrade,release-upgrade,dist-upgrade,assumeyes,usbvm:,netvm:,updatevm:,skip-template-upgrade,skip-standalone-upgrade
drop also short options that don't exist anymore

2023-07-25 00:51 UTC, marmarek commented on scripts/upgrade-template-standalone.sh
> +    sed -i 's/arch=amd64/arch=amd64\ signed-by=\/usr\/share\/keyrings\/apt-qubes-archive-keyring.gpg/g' /etc/apt/sources.list.d/qubes-r4.list
```suggestion
    sed -i 's/arch=amd64/arch=amd64\ signed-by=\/usr\/share\/keyrings\/apt-qubes-archive-keyring-4.2.gpg/g' /etc/apt/sources.list.d/qubes-r4.list
```

2023-07-25 00:51 UTC, marmarek commented on qubes-dist-upgrade.sh
>          qubes-dom0-update $dnf_opts --downloadonly $packages
Add `--force-xen-upgrade` to avoid the prompt to shutdown all VMs.

2023-07-28 10:36 UTC, noskb commented on scripts/upgrade-template-standalone.sh
> +    dnf swap--allowerasing pulseaudio pipewire-pulseaudio
```suggestion
    dnf swap --allowerasing pulseaudio pipewire-pulseaudio
```

2023-07-28 13:34 UTC, marmarek commented
PipelineRetry

2023-07-28 17:51 UTC, marmarek commented on qubes-dist-upgrade.sh
> +          new_kernel="${new_kernel%.qubes}"  # TODO: does this work? check with tests
No, it doesn't, there may be `6.1.38-1.qubes.fc37`. Try `new_kernel="${new_kernel/.qubes/}"`

2023-08-05 13:33 UTC, marmarek requested changes

2023-08-05 13:33 UTC, marmarek commented on qubes-dist-upgrade.sh
> +    if [ -e "/etc/qubes-rpc/policy/qubes.UpdatesProxy" ]; then
This condition isn't really applicable for new policy

2023-08-05 13:33 UTC, marmarek commented on qubes-dist-upgrade.sh
> +      mapfile -t updates_proxy_new < <(grep qubes.UpdatesProxy /etc/qubes/policy.d/*policy | grep '^\s*[^#].*target=' | cut -d = -f 2)
Technically it should be `*.policy`

2023-08-05 13:33 UTC, marmarek commented on qubes-dist-upgrade.sh
> +        echo "--> If upgrade to 4.2 fails, you can restore your dom0 snapshot after booting from a bootable device and using sudo lvconvert --merge $root_group_name/Qubes41UpgradeBackup. Reboot after
It seems I was wrong, it is possible to do that from running system, and then reboot.

2023-08-05 13:33 UTC, marmarek commented on qubes-dist-upgrade.sh
> +        lvremove "$root_group_name/Qubes41UpgradeBackup"
if assumeyes==1, there should be `-f` too.

2023-08-14 14:09 UTC, marmarek approved these changes

2023-08-14 14:09 UTC, merged